import { readFile } from "node:fs/promises"
import { readVersionedVShape } from "../../packages/formats/src/vshape"
import { expect, test } from "./fixtures"
import { confirmSketchPlane, drawRectangle } from "./sketch-helpers"

test("undoes saved feature edits and deletion, then reopens and copies replayable history", async ({
  page,
}) => {
  test.setTimeout(180_000)
  await page.goto("/")
  await expect(page.getByText("Saved in this browser", { exact: true })).toBeVisible()
  const toolbar = page.getByRole("toolbar", { name: "Model commands" })
  const undo = toolbar.getByRole("button", { name: "Undo", exact: true })
  const redo = toolbar.getByRole("button", { name: "Redo", exact: true })
  const viewport = page.getByRole("region", { name: "3D viewport" })
  await expect(undo).toBeDisabled()
  await toolbar.getByRole("button", { name: "Box", exact: true }).click()
  const create = page.getByRole("form", { name: "Create box" })
  await create.getByRole("combobox", { name: "Width", exact: true }).fill("20 mm")
  await create.getByRole("button", { name: "Create box", exact: true }).click()
  const box = page.getByRole("treeitem", { name: "Box 1", exact: true })
  await expect(box).toBeVisible()
  await expect(viewport).toHaveAttribute("data-rendered-feature-count", "1")
  await undo.click()
  await expect(box).toHaveCount(0)
  await expect(viewport).toHaveAttribute("data-rendered-feature-count", "0")
  await redo.click()
  await expect(box).toBeVisible()
  await box.click()
  const edit = page.getByRole("form", { name: "Edit box" })
  await edit.getByRole("combobox", { name: "Width", exact: true }).fill("30 mm")
  await edit.getByRole("button", { name: "Update box", exact: true }).click()
  await expect(edit).toHaveCount(0)
  await page.keyboard.press("ControlOrMeta+z")
  await expect(redo).toBeEnabled()
  await box.click()
  await expect(edit.getByRole("combobox", { name: "Width", exact: true })).toHaveValue("20 mm")
  await edit.getByRole("button", { name: "Cancel", exact: true }).click()
  await page.keyboard.press("ControlOrMeta+Shift+z")
  await expect(redo).toBeDisabled()
  await box.click()
  await expect(edit.getByRole("combobox", { name: "Width", exact: true })).toHaveValue("30 mm")
  await page.getByRole("button", { name: "Delete feature", exact: true }).click()
  await page
    .getByRole("alertdialog")
    .getByRole("button", { name: "Delete feature", exact: true })
    .click()
  await expect(box).toHaveCount(0)
  await undo.click()
  await expect(box).toBeVisible()
  await expect(viewport).toHaveAttribute("data-rendered-feature-count", "1")
  await page.reload()
  await expect(viewport).toHaveAttribute("data-rendered-feature-count", "1")
  await expect(undo).toBeDisabled()
  await expect(redo).toBeDisabled()
  await box.click()
  await expect(edit.getByRole("combobox", { name: "Width", exact: true })).toHaveValue("30 mm")
  await edit.getByRole("button", { name: "Cancel", exact: true }).click()

  await page.getByRole("button", { name: "Project…" }).click()
  const projects = page.getByRole("dialog", { name: "Projects" })
  const downloading = page.waitForEvent("download")
  await projects.getByRole("button", { name: "Download .vshape" }).click()
  const file = await (await downloading).path()
  if (!file) throw new Error("The project backup was not retained.")
  const archive = await readVersionedVShape(new Uint8Array(await readFile(file)))
  expect(archive.ok).toBe(true)
  if (!archive.ok || archive.value.version !== 2)
    throw new Error("Expected a replay-proven v2 backup.")
  expect(
    archive.value.project.versionedEvents.filter(
      (event) => event.type === "org.vibeshape.document.restored",
    ),
  ).toHaveLength(5)
  await page.getByRole("button", { name: "Project…" }).click()
  await projects.getByRole("button", { name: /Duplicate .*revision/ }).click()
  const copy = projects.getByRole("listitem").filter({ hasText: "Untitled project copy" })
  await copy.getByRole("button", { name: /Open .*revision/ }).click()
  await expect(viewport).toHaveAttribute("data-rendered-feature-count", "1")
  await expect(undo).toBeDisabled()
  await box.click()
  await expect(edit.getByRole("combobox", { name: "Width", exact: true })).toHaveValue("30 mm")
})

test("keeps sketch draft undo separate and truncates committed redo after a new sketch", async ({
  page,
}) => {
  test.setTimeout(120_000)
  await page.goto("/")
  await expect(page.getByText("Saved in this browser", { exact: true })).toBeVisible()
  const toolbar = page.getByRole("toolbar", { name: "Model commands" })
  await toolbar.getByRole("button", { name: "Create sketch", exact: true }).click()
  await confirmSketchPlane(page, "xy")
  await drawRectangle(page)
  await page.getByRole("button", { name: "Finish sketch", exact: true }).click()
  const sketch = page.getByRole("treeitem", { name: "Sketch 1", exact: true })
  await expect(sketch).toBeVisible()
  await toolbar.getByRole("button", { name: "Undo", exact: true }).click()
  await expect(sketch).toHaveCount(0)
  await expect(toolbar.getByRole("button", { name: "Redo", exact: true })).toBeEnabled()
  await toolbar.getByRole("button", { name: "Create sketch", exact: true }).click()
  await confirmSketchPlane(page, "xz")
  await drawRectangle(page)
  await page.keyboard.press("ControlOrMeta+z")
  await page.keyboard.press("ControlOrMeta+Shift+z")
  await page.getByRole("button", { name: "Finish sketch", exact: true }).click()
  await expect(sketch).toBeVisible()
  await expect(toolbar.getByRole("button", { name: "Redo", exact: true })).toBeDisabled()
  await page.reload()
  await expect(sketch).toBeVisible()
})
