import type { Locator } from "@playwright/test"
import { expect, test } from "./fixtures"

async function expectMetric(panel: Locator, label: string, value: string) {
  await expect(
    panel
      .locator("dt", { hasText: new RegExp(`^${label}$`) })
      .locator("..")
      .locator("dd"),
  ).toHaveText(value)
}

test("measures exact box and cylinder outputs, converts units, and refreshes after edit and reopen", async ({
  page,
}) => {
  test.setTimeout(180_000)
  await page.setViewportSize({ width: 1024, height: 900 })
  await page.emulateMedia({ reducedMotion: "reduce" })
  await page.goto("/")
  await expect(page.getByText("Saved in this browser", { exact: true })).toBeVisible()
  const toolbar = page.getByRole("toolbar", { name: "Model commands" })
  await toolbar.getByRole("button", { name: "Box", exact: true }).click()
  const box = page.getByRole("form", { name: "Create box" })
  await box.getByRole("combobox", { name: "Width", exact: true }).fill("10 mm")
  await box.getByRole("combobox", { name: "Depth", exact: true }).fill("20 mm")
  await box.getByRole("combobox", { name: "Height", exact: true }).fill("30 mm")
  await box.getByRole("button", { name: "Create box" }).click()
  await expect(page.getByRole("treeitem", { name: "Box 1", exact: true })).toBeVisible()
  const boxBody = page.locator("[data-body-id]").getByRole("treeitem")
  await expect(boxBody).toHaveCount(1)
  await boxBody.click()
  const measure = toolbar.getByRole("button", { name: "Measure", exact: true })
  await measure.focus()
  await page.keyboard.press("Enter")
  const panel = page.getByRole("complementary", { name: "Measure", exact: true })
  await expect(boxBody).toHaveAttribute("aria-selected", "true")
  await expectMetric(panel, "Volume", "6,000 mm³")
  await expectMetric(panel, "Surface area", "2,200 mm²")
  await expectMetric(panel, "Width", "10 mm")
  await expectMetric(panel, "Depth", "20 mm")
  await expectMetric(panel, "Height", "30 mm")
  await panel.getByRole("button", { name: "Close", exact: true }).click()
  await toolbar.getByRole("button", { name: "Cylinder", exact: true }).click()
  const cylinder = page.getByRole("form", { name: "Create cylinder" })
  await cylinder.getByRole("combobox", { name: "Radius", exact: true }).fill("5 mm")
  await cylinder.getByRole("combobox", { name: "Height", exact: true }).fill("10 mm")
  await cylinder.getByRole("button", { name: "Create cylinder" }).click()
  await expect(page.getByRole("treeitem", { name: "Cylinder 1", exact: true })).toBeVisible()
  await measure.click()
  const all = panel.getByRole("button", { name: "Show all current outputs" })
  if (await all.isVisible()) await all.click()
  const output = panel.getByRole("combobox", { name: "Body output", exact: true })
  await output.selectOption({ label: "Cylinder 1" })
  await expectMetric(panel, "Volume", "785.3982 mm³")
  await expectMetric(panel, "Surface area", "471.2389 mm²")
  await expectMetric(panel, "Width", "10 mm")
  await expectMetric(panel, "Depth", "10 mm")
  await expectMetric(panel, "Height", "10 mm")
  await output.selectOption({ label: "Box 1" })
  await expectMetric(panel, "Volume", "6,000 mm³")
  await page.locator("html").evaluate((element) => element.classList.remove("dark"))
  await page.screenshot({
    animations: "disabled",
    path: test.info().outputPath("measurements-light.png"),
  })
  await panel.getByRole("button", { name: "Close", exact: true }).click()
  await page.getByRole("treeitem", { name: "Box 1", exact: true }).click()
  const edit = page.getByRole("form", { name: "Edit box" })
  await edit.getByRole("combobox", { name: "Height", exact: true }).fill("40 mm")
  await edit.getByRole("button", { name: "Update box" }).click()
  await expect(edit).not.toBeVisible()
  await measure.click()
  if (await all.isVisible()) await all.click()
  await output.selectOption({ label: "Box 1" })
  await expectMetric(panel, "Volume", "8,000 mm³")
  await expectMetric(panel, "Surface area", "2,800 mm²")
  await panel.getByRole("button", { name: "Close", exact: true }).click()
  await page.getByRole("button", { name: "Project units: mm, deg" }).click()
  const units = page.getByRole("dialog", { name: "Project units" })
  await units.getByRole("combobox", { name: "Length unit" }).selectOption("cm")
  await units.getByRole("button", { name: "Apply project units" }).click()
  await expect(units).not.toBeVisible()
  await page.reload()
  await expect(page.getByText("Saved in this browser", { exact: true })).toBeVisible()
  await measure.click()
  if (await all.isVisible()) await all.click()
  await output.selectOption({ label: "Box 1" })
  await expectMetric(panel, "Volume", "8 cm³")
  await expectMetric(panel, "Surface area", "28 cm²")
  await expectMetric(panel, "Width", "1 cm")
  await expectMetric(panel, "Depth", "2 cm")
  await expectMetric(panel, "Height", "4 cm")
  await page.locator("html").evaluate((element) => element.classList.add("dark"))
  await page.screenshot({
    animations: "disabled",
    path: test.info().outputPath("measurements-dark.png"),
  })
  // A 512 CSS-pixel viewport represents a 1024-pixel window at 200% browser zoom.
  await page.setViewportSize({ width: 512, height: 450 })
  const close = panel.getByRole("button", { name: "Close", exact: true })
  await close.scrollIntoViewIfNeeded()
  await expect(close).toBeInViewport({ ratio: 1 })
  await output.scrollIntoViewIfNeeded()
  await expect(output).toBeInViewport({ ratio: 1 })
  const value = panel.locator("dd", { hasText: "8 cm³" })
  await value.scrollIntoViewIfNeeded()
  await expect(value).toBeInViewport({ ratio: 1 })
  await expect(page.locator("html")).toHaveJSProperty("scrollWidth", 512)
  await page.screenshot({
    animations: "disabled",
    path: test.info().outputPath("measurements-zoom.png"),
  })
  await page.getByRole("button", { name: "Collapse task panel", exact: true }).click()
  await expect(panel).not.toBeVisible()
  await page.getByRole("button", { name: "Open task panel", exact: true }).click()
  await expectMetric(panel, "Volume", "8 cm³")
  await close.click()
  await expect(panel).not.toBeVisible()
})
