async function createVibeShapeSketchSolver(moduleArg={}){var Module=moduleArg;var ba=!!globalThis.window,ca=!!globalThis.WorkerGlobalScope,p=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer";if(p){let {createRequire:a}=await import("node:module");var u=a(import.meta.url)}var x=(a,b)=>{throw b;},da=import.meta.url,y="",ea,z;if(p){var fa=u("node:fs");da.startsWith("file:")&&(y=u("node:path").dirname(u("node:url").fileURLToPath(da))+"/");z=a=>{a=ha(a)?new URL(a):a;return fa.readFileSync(a)};ea=async a=>{a=ha(a)?new URL(a):a;return fa.readFileSync(a,
void 0)};process.argv.slice(2);x=(a,b)=>{process.exitCode=a;throw b;}}else if(ba||ca){try{y=(new URL(".",da)).href}catch{}ca&&(z=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ea=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var ia=console.log.bind(console),A=console.error.bind(console),B=!1,ja,ha=a=>a.startsWith("file://");function ka(){if(!C?.buffer?.resizable){var a=
E.buffer;C=new Int8Array(a);F=new Int16Array(a);G=new Uint8Array(a);H=new Uint16Array(a);I=new Int32Array(a);J=new Uint32Array(a);la=new Float32Array(a);ma=new Float64Array(a);na=new BigInt64Array(a);oa=new BigUint64Array(a)}}function pa(){var a=Module.preRun;a&&(typeof a=="function"&&(a=[a]),qa.push(...a));for(a=qa;a.length>0;)a.shift()(Module)}function sa(){var a=Module.postRun;a&&(typeof a=="function"&&(a=[a]),ta.push(...a));for(a=ta;a.length>0;)a.shift()(Module)}function ua(a){Module.onAbort?.(a);
a=`Aborted(${a})`;A(a);B=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var va;async function wa(a){try{var b=await ea(a);return new Uint8Array(b)}catch{}if(z)a=z(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){A(`failed to asynchronously prepare wasm: ${d}`),ua(d)}}async function ya(a){var b=va;if(!p)try{var c=fetch(b,{credentials:"same-origin"});
return await WebAssembly.instantiateStreaming(c,a)}catch(d){A(`wasm streaming compile failed: ${d}`),A("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var C,ta=[],qa=[],K=!0,J;class Aa{constructor(a){this.W=a-24}init(a,b){J[this.W+16>>2]=0;J[this.W+4>>2]=a;J[this.W+8>>2]=b}}var Ba=0,L={},Ca=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function M(a){return this.R(J[a>>2])}var N=
{},O={},P={};class Da extends Error{constructor(a){super(a);this.name="InternalError"}}var Ea=(a,b,c)=>{function d(g){g=c(g);if(g.length!==a.length)throw new Da("Mismatched type converter count");for(var l=0;l<a.length;++l)Q(a[l],g[l])}a.forEach(g=>P[g]=b);var e=Array(b.length),f=[],h=0;for(let [g,l]of b.entries())O.hasOwnProperty(l)?e[g]=O[l]:(f.push(l),N.hasOwnProperty(l)||(N[l]=[]),N[l].push(()=>{e[g]=O[l];++h;h===f.length&&d(e)}));0===f.length&&d(e)},G,R=a=>{for(var b="";;){var c=G[a++];if(!c)return b;
b+=String.fromCharCode(c)}};class S extends Error{constructor(a){super(a);this.name="BindingError"}}var Fa=a=>{throw new S(a);};function Ga(a,b,c={}){var d=b.name;if(!a)throw new S(`type "${d}" must have a positive integer typeid pointer`);if(O.hasOwnProperty(a)){if(c.ea)return;throw new S(`Cannot register type '${d}' twice`);}O[a]=b;delete P[a];N.hasOwnProperty(a)&&(b=N[a],delete N[a],b.forEach(e=>e()))}function Q(a,b,c={}){return Ga(a,b,c)}var F,H,I,na,oa,Ha=(a,b,c)=>{switch(b){case 1:return c?
d=>C[d]:d=>G[d];case 2:return c?d=>F[d>>1]:d=>H[d>>1];case 4:return c?d=>I[d>>2]:d=>J[d>>2];case 8:return c?d=>na[d>>3]:d=>oa[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ia=[],T=[0,1,,1,null,1,!0,1,!1,1],Ja=a=>{a>9&&0===--T[a+1]&&(T[a]=void 0,Ia.push(a))},U=a=>{if(!a)throw new S(`Cannot use deleted val. handle = ${a}`);return T[a]},V=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:let b=Ia.pop()||T.length;T[b]=a;T[b+1]=
1;return b}},Ka={name:"emscripten::val",R:a=>{var b=U(a);Ja(a);return b},S:(a,b)=>V(b),V:M,T:null},la,ma,La=(a,b)=>{switch(b){case 4:return function(c){return this.R(la[c>>2])};case 8:return function(c){return this.R(ma[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}};function Ma(a){for(var b=1;b<a.length;++b)if(a[b]!==null&&a[b].T===void 0)return!0;return!1}var Na=(a,b)=>{var c=Module;if(void 0===c[a].U){var d=c[a];c[a]=function(...e){if(!c[a].U.hasOwnProperty(e.length))throw new S(`Function '${b}' called with an invalid number of arguments (${e.length}) - expects one of (${c[a].U})!`);
return c[a].U[e.length].apply(this,e)};c[a].U=[];c[a].U[d.X]=d}},Oa=(a,b,c)=>{if(Module.hasOwnProperty(a)){if(void 0===c||void 0!==Module[a].U&&void 0!==Module[a].U[c])throw new S(`Cannot register public name '${a}' twice`);Na(a,a);if(Module[a].U.hasOwnProperty(c))throw new S(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);Module[a].U[c]=b}else Module[a]=b,Module[a].X=c},Pa=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(J[b+d*4>>2]);return c},Qa=[],W=(a,b)=>
{a=R(a);var c;(c=Qa[b])||(Qa[b]=c=Ta.get(b));if(typeof c!="function")throw new S(`unknown function pointer with signature ${a}: ${b}`);return c};class Ua extends Error{}var Wa=a=>{a=Va(a);var b=R(a);X(a);return b},Xa=(a,b)=>{function c(f){e[f]||O[f]||(P[f]?P[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Ua(`${a}: `+d.map(Wa).join([", "]));},Ya=a=>{a=a.trim();var b=a.indexOf("(");return b===-1?a:a.slice(0,b)},Za=globalThis.TextDecoder&&new TextDecoder,$a=(a,b,c,d)=>{c=b+c;
if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},ab=(a,b=0,c,d)=>{c=$a(a,b,c,d);if(c-b>16&&a.buffer&&Za)return Za.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if((e&224)==192)d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=(e&240)==224?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;e<65536?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},bb=globalThis.TextDecoder?new TextDecoder("utf-16le"):
void 0,cb=(a,b,c)=>{a>>=1;b=$a(H,a,b/2,c);if(b-a>16&&bb)return bb.decode(H.subarray(a,b));for(c="";a<b;++a)c+=String.fromCharCode(H[a]);return c},db=(a,b,c=2147483647)=>{if(c<2)return 0;c-=2;var d=b;c=c<a.length*2?c/2:a.length;for(var e=0;e<c;++e)F[b>>1]=a.charCodeAt(e),b+=2;F[b>>1]=0;return b-d},eb=a=>a.length*2,fb=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=J[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},gb=(a,b,c=2147483647)=>{if(c<4)return 0;var d=b;c=d+c-4;for(var e=
0;e<a.length;++e){var f=a.codePointAt(e);f>65535&&e++;I[b>>2]=f;b+=4;if(b+4>c)break}I[b>>2]=0;return b-d},hb=a=>{for(var b=0,c=0;c<a.length;++c)a.codePointAt(c)>65535&&c++,b+=4;return b},ib=0,jb=[],kb=a=>{var b=jb.length;jb.push(a);return b},lb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d){var e=d,f=J[b+d*4>>2],h=O[f];if(void 0===h)throw a=`${`parameter ${d}`} has unknown type ${Wa(f)}`,new S(a);c[e]=h}return c},mb=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(J[b>>2]=V(d));return a},nb={},ob=a=>{var b=nb[a];
return b===void 0?R(a):b},Y={},pb=a=>{ja=a;K||ib>0||(Module.onExit?.(a),B=!0);x(a,new za(a))},qb=a=>{if(!B)try{a()}catch(b){b instanceof za||b=="unwind"||x(1,b)}finally{if(!(K||ib>0))try{ja=a=ja,pb(a)}catch(b){b instanceof za||b=="unwind"||x(1,b)}}},rb=[null,[],[]],sb=()=>{if(p){var a=u("node:crypto");return b=>(a.randomFillSync(b),0)}return b=>(crypto.getRandomValues(b),0)},tb=a=>(tb=sb())(a);Module.noExitRuntime&&(K=Module.noExitRuntime);Module.print&&(ia=Module.print);Module.printErr&&(A=Module.printErr);
var Z=Module.preInit;if(Z)for(typeof Z=="function"&&(Module.preInit=Z=[Z]);Z.length>0;)Z.shift()();var ub,X,Va,vb,E,Ta,wb={c:(a,b,c)=>{(new Aa(a)).init(b,c);Ba++;ua()},E:()=>ua(""),u:a=>{var b=L[a];delete L[a];var c=b.fa,d=b.ga,e=b.Y,f=e.map(h=>h.da).concat(e.map(h=>h.ia));Ea([a],f,h=>{var g={},l,k;for([l,k]of e.entries()){let n=h[l],r=k.aa,m=k.ba,v=h[l+e.length],D=k.ha,aa=k.ja;g[k.$]={read:q=>n.R(r(m,q)),write:(q,w)=>{var t=[];D(aa,q,v.S(t,w));Ca(t)},optional:n.optional}}return[{name:b.name,R:n=>
{var r={},m;for(m in g)r[m]=g[m].read(n);d(n);return r},S:(n,r)=>{for(var m in g)if(!(m in r||g[m].optional))throw new TypeError(`Missing field: "${m}"`);var v=c();for(m in g)g[m].write(v,r[m]);n!==null&&n.push(d,v);return v},V:M,T:d}]})},t:(a,b,c,d,e)=>{b=R(b);d=d===0n;var f=h=>h;if(d){let h=c*8;f=g=>BigInt.asUintN(h,g);e=f(e)}Q(a,{name:b,R:f,S:(h,g)=>{typeof g=="number"&&(g=BigInt(g));return g},V:Ha(b,c,!d),T:null})},H:(a,b,c,d)=>{b=R(b);Q(a,{name:b,R:function(e){return!!e},S:function(e,f){return f?
c:d},V:function(e){return this.R(G[e])},T:null})},n:(a,b,c)=>{a=R(a);Ea([],[b],d=>{d=d[0];Module[a]=d.R(c);return[]})},F:a=>Q(a,Ka),s:(a,b,c)=>{b=R(b);Q(a,{name:b,R:d=>d,S:(d,e)=>e,V:La(b,c),T:null})},q:(a,b,c,d,e,f,h)=>{var g=Pa(b,c);a=R(a);a=Ya(a);e=W(d,e);Oa(a,function(){Xa(`Cannot call ${a} due to unbound types`,g)},b-1);Ea([],g,l=>{var k=[l[0],null].concat(l.slice(1));l=a;var n=a;var r=e,m=k.length;if(m<2)throw new S("argTypes array size mismatch! Must at least get return value and receiver (this) types!");
var v=k[1]!==null&&!1,D=Ma(k),aa=!k[0].Z,q=k[0],w=k[1];r=[n,Fa,r,f,Ca,q.R.bind(q),w?.S.bind(w)];for(q=2;q<m;++q)w=k[q],r.push(w.S.bind(w));if(!D)for(q=v?1:2;q<k.length;++q)k[q].T!==null&&r.push(k[q].T);D=Ma(k);q=k.length-2;var t=[];w=["fn"];v&&w.push("thisWired");for(m=0;m<q;++m)t.push(`arg${m}`),w.push(`arg${m}Wired`);t=t.join();w=w.join();t=`return function (${t}) {\n`;D&&(t+="var destructors = [];\n");var Ra=D?"destructors":"null",ra="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");
v&&(t+=`var thisWired = toClassParamWire(${Ra}, this);\n`);for(m=0;m<q;++m){var Sa=`toArg${m}Wire`;t+=`var arg${m}Wired = ${Sa}(${Ra}, arg${m});\n`;ra.push(Sa)}t+=(aa||h?"var rv = ":"")+`invoker(${w});\n`;if(D)t+="runDestructors(destructors);\n";else for(m=v?1:2;m<k.length;++m)v=m===1?"thisWired":`arg${m-2}Wired`,k[m].T!==null&&(t+=`${v}_dtor(${v});\n`,ra.push(`${v}_dtor`));aa&&(t+="var ret = fromRetWire(rv);\nreturn ret;\n");k=(new Function(ra,t+"}\n"))(...r);n=Object.defineProperty(k,"name",{value:n});
k=b-1;if(!Module.hasOwnProperty(l))throw new Da("Replacing nonexistent public symbol");void 0!==Module[l].U&&void 0!==k?Module[l].U[k]=n:(Module[l]=n,Module[l].X=k);return[]})},i:(a,b,c,d,e)=>{b=R(b);var f=g=>g;if(d===0){var h=32-8*c;f=g=>g<<h>>>h;e=f(e)}Q(a,{name:b,R:f,S:(g,l)=>l,V:Ha(b,c,d!==0),T:null})},b:(a,b,c)=>{function d(f){return new e(C.buffer,J[f+4>>2],J[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];
c=R(c);Q(a,{name:c,R:d,V:d},{ea:!0})},G:(a,b)=>{b=R(b);Q(a,{name:b,R(c){var d=(d=c+4)?ab(G,d,J[c>>2],!0):"";X(c);return d},S(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e,f=typeof d=="string";if(!(f||ArrayBuffer.isView(d)&&d.BYTES_PER_ELEMENT==1))throw new S("Cannot pass non-string to std::string");var h;if(f)for(e=h=0;e<d.length;++e){var g=d.charCodeAt(e);g<=127?h++:g<=2047?h+=2:g>=55296&&g<=57343?(h+=4,++e):h+=3}else h=d.length;e=h;h=ub(4+e+1);g=h+4;J[h>>2]=e;if(f){if(f=g,g=e+1,e=G,
g>0){g=f+g-1;for(var l=0;l<d.length;++l){var k=d.codePointAt(l);if(k<=127){if(f>=g)break;e[f++]=k}else if(k<=2047){if(f+1>=g)break;e[f++]=192|k>>6;e[f++]=128|k&63}else if(k<=65535){if(f+2>=g)break;e[f++]=224|k>>12;e[f++]=128|k>>6&63;e[f++]=128|k&63}else{if(f+3>=g)break;e[f++]=240|k>>18;e[f++]=128|k>>12&63;e[f++]=128|k>>6&63;e[f++]=128|k&63;l++}}e[f]=0}}else G.set(d,g);c!==null&&c.push(X,h);return h},V:M,T(c){X(c)}})},m:(a,b,c)=>{c=R(c);if(b===2){var d=cb;var e=db;var f=eb}else d=fb,e=gb,f=hb;Q(a,
{name:c,R:h=>{var g=d(h+4,J[h>>2]*b,!0);X(h);return g},S:(h,g)=>{if(typeof g!="string")throw new S(`Cannot pass non-string to C++ string type ${c}`);var l=f(g),k=ub(4+l+b);J[k>>2]=l/b;e(g,k+4,l+b);h!==null&&h.push(X,k);return k},V:M,T(h){X(h)}})},J:(a,b,c,d,e,f)=>{L[a]={name:R(b),fa:W(c,d),ga:W(e,f),Y:[]}},j:(a,b,c,d,e,f,h,g,l,k)=>{L[a].Y.push({$:R(b),da:c,aa:W(d,e),ba:f,ia:h,ha:W(g,l),ja:k})},I:(a,b)=>{b=R(b);Q(a,{Z:!0,name:b,R:()=>{},S:()=>{}})},C:()=>{K=!1;ib=0},d:(a,b,c)=>{var d;[b,...d]=lb(a,
b);var e=b.S.bind(b),f=d.map(l=>l.V.bind(l));a--;var h={toValue:U};a=f.map((l,k)=>{var n=`argFromPtr${k}`;h[n]=l;return`${n}(args${k?"+"+k*8:""})`});switch(c){case 0:var g="toValue(handle)";break;case 2:g="new (toValue(handle))";break;case 3:g="";break;case 1:h.getStringOrSymbol=ob,g="toValue(handle)[getStringOrSymbol(methodName)]"}g+=`(${a})`;b.Z||(h.toReturnWire=e,h.emval_returnValue=mb,g=`return emval_returnValue(toReturnWire, destructorsRef, ${g})`);g=`return function (handle, methodName, destructorsRef, args) {\n${g}\n}`;
c=(new Function(Object.keys(h),g))(...Object.values(h));b=`methodCaller<(${d.map(l=>l.name)}) => ${b.name}>`;return kb(Object.defineProperty(c,"name",{value:b}))},a:Ja,k:a=>{if(!a)return V(globalThis);a=ob(a);return V(globalThis[a])},p:(a,b)=>{a=U(a);b=U(b);return V(a[b])},h:a=>{a>9&&(T[a+1]+=1)},f:(a,b,c,d,e)=>jb[a](b,c,d,e),o:a=>V(ob(a)),e:a=>{var b=U(a);Ca(b);Ja(a)},v:(a,b)=>{Y[a]&&(clearTimeout(Y[a].id),delete Y[a]);if(!b)return 0;var c=setTimeout(()=>{delete Y[a];qb(()=>vb(a,performance.now()))},
b);Y[a]={id:c,ka:b};return 0},A:function(a,b,c){if(!(a>=0&&a<=3))return 28;na[c>>3]=BigInt(Math.round((a===0?Date.now():performance.now())*1E3*1E3));return 0},r:a=>{console.error(a?ab(G,a):"")},g:()=>Date.now(),l:()=>performance.now(),w:a=>{var b=G.length;a>>>=0;if(a>67108864)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(67108864,Math.ceil(Math.max(a,d)/65536)*65536)-E.buffer.byteLength+65535)/65536|0;try{E.grow(d);ka();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},
z:()=>52,x:function(){return 70},y:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var h=J[b>>2],g=J[b+4>>2];b+=8;for(var l=0;l<g;l++){var k=a,n=G[h+l],r=rb[k];n&&n!==10?r.push(n):((k===1?ia:A)(ab(r)),r.length=0)}e+=g}J[d>>2]=e;return 0},B:pb,D:(a,b)=>tb(G.subarray(a,a+b))},xb;xb=await (async function(){function a(d){d=xb=d.exports;ub=d.M;X=d.N;Va=d.O;vb=d.Q;E=d.K;Ta=d.P;ka();return xb}var b={a:wb},c=Module.instantiateWasm;if(c)return new Promise(d=>{c(b,e=>d(a(e)))});va??=Module.locateFile?Module.locateFile?
Module.locateFile("vibeshape_slvs.wasm",y):y+"vibeshape_slvs.wasm":(new URL("vibeshape_slvs.wasm",import.meta.url)).href;return function(d){return a(d.instance)}(await ya(b))}());await (async function(){pa();var a=Module.setStatus;a&&(a("Running..."),await new Promise(b=>setTimeout(b,1)),setTimeout(a,1,""));B||(xb.L(),Module.onRuntimeInitialized?.(),sa())}());;return Module}export default createVibeShapeSketchSolver;
